general:
  clientUrl: http://localhost:8080/wizard
  secret: insecure-demo-dsw-secret
  rsaPrivateKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDAip4YwYPi13kc
    UERJiOQPLJfA9GhPvjSqBlyhfmerf+ruMComuWlZQ13QqeCyT1/kOcimRivGM/lC
    jjnfQ3FoS5DMUwLrpvPJDH8T27hZ51WDh12bT6lHUhruju1xfQqHYIJ5qm6cigdU
    1951XLESKtJgpkt4uqBK0eDBXY5ZXBBE+MzRqzJKcpMPv6kXEJp0Lenm5Gqtma04
    +iVUh9KU2l1V9vwMqjlyF/DplaABR+YIKTwWKqjHuHTsSuZBAsU5tX0LsGU8uCJd
    UYwztfHjQuKFmEWAmXnZeVaFxUqaxCUuKwUSmGjMORcC3zWr7LZoyY/9dS3TAXlW
    ln1/5DIlAgMBAAECggEACvWlwh4uj6VZAELHxrFc3RanHK7//dBp1wCKgHbD5LMt
    s2Xyc3nVhH5p9j91MGRSpP8IOM60HZGslbYN/UAthS5BjVMJG4WWFgX432LmWQrq
    umEXwIg5FOIx8XPmEbIR/PRO+PXs9EqD2FFHssGv715lbMyKbZ84RVbLYE/rxl8Q
    LNTYsgsC7y1gY1VMPTLMvwlqaXHCGNgA6aKp+cLGjFhLUcDmjM9aFIygQYvhBm3w
    UZjip7vJk7h4m4lXlcjSUkzlyhh+nmM1UKPuXHTvbVWyQN0qU+MjOV6+AW2ZRfSC
    xtuCv7JXmjDn6imr2n7aavFgRpdLA+Ns4Mp9/GQUkQKBgQD0dj6avKBG0ITMSIsS
    l/tCn673W29387DL+4d7VihlcImhqmnoZZZx8D54XiDWUTBUOcOdNw7a8L8at5Uy
    04EM2jBFzT+3yxRbVgaeXz/8celhhYo5RWFRTpqkAGZPRRWhfXAcvCWQ8Bqxvrsz
    wjHeixAQo9omMCeeFaxHk7g7VwKBgQDJoQj7iFp1Sl0k4ifTUb8uTyjRvNr7/ZE/
    jlhWrkbPTxtyrUr0vHe4FkdhgJOhSZwFIPByMfNAq4RkarUoQrYkiDM+VxksHuOz
    qLlKzevIYOmJHU09E0LeuL3MznhvUJA20YNnKCXPsrBlRnKKjGDamQDr49/Ducvq
    AcST/QyM4wKBgQCRoNMgmNed99/0Vg7LD9C1Wqz/W+/mdDxQ99E4rxW3gDftH7ih
    ocriqyx7xg8nvQveUN7wC/mEgcBGaTCvK4IIJv50xpV7prXEx1WACNv0ReOynbu+
    7E7SAdJrenV4KX5+Slx8MbTrR62PT0Dzz26n1Q3H6+QrtaoUKXMM3Ln2VwKBgQCF
    sgICx6czntukWVGPDeV3D4ZBjLin3rsxKXHqCCVr0UiiAcZyAYZgymUKgfdiOyz5
    OZ42GmjxuMlQzHDTAWlFUAqqi5ZlaxYRSw+SSnjNpXU1NfjBRsRQaq9v3nh9Vy5J
    KyO2gyiPUC0m+k95Dxwp1sqFn9QANHLB9+ohNunbgQKBgGisecKJ5Ir3XpbWVzjl
    NF3DcZonHZ2onGIhO5P/+xR8iIW6St65l1jcmm/oCuOEQh8wMp12yz7Fs0ZmzWaq
    jdrXdesJRMB23s+cPfLDJKv/sqZFQfxhvp4c8SIy79hyGhwj2NrhqzBcSTsU1LzB
    V4aOMoVXjPOpMHd6TJbmTTRx
    -----END PRIVATE KEY-----

database:
  connectionString: postgresql://postgres:postgres@postgres:5432/engine-wizard

s3:
  url: http://host.docker.internal:9000
  username: GK0123456789abcdef01234567
  password: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  bucket: engine-wizard
  region: garage

mail:
  enabled: false
  name:
  email:
  provider: smtp
  smtp:
    host:
    port:
    security: plain # plain | ssl | starttls
    username:
    password:
