server {
    listen 8080;
    server_name _;

    location /plugins/ {
        rewrite ^/plugins/(.*)$ /$1 break;
        proxy_pass http://garage:3902;
        proxy_set_header Host plugins.web.garage.localhost;

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Allow-Headers "*" always;
        add_header Access-Control-Expose-Headers "Content-Length, Content-Type, ETag" always;

        if ($request_method = OPTIONS) {
            add_header Content-Length 0;
            add_header Content-Type text/plain;
            return 204;
        }
    }

    location / {
        proxy_pass http://garage:3902;
        proxy_set_header Host plugins.web.garage.localhost;

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Allow-Headers "*" always;
        add_header Access-Control-Expose-Headers "Content-Length, Content-Type, ETag" always;

        if ($request_method = OPTIONS) {
            add_header Content-Length 0;
            add_header Content-Type text/plain;
            return 204;
        }
    }
}
